/**
 * The passive tree: ~600 nodes laid out in six attribute sectors around a central start.
 *
 *   Might (STR) · Finesse (DEX) · Arcana (INT) and the hybrids between them.
 *
 * Each sector has a spine of attribute nodes, wheel clusters (a notable ringed by minors), skill
 * clusters (a node that unlocks an active skill plus three enhancements of that skill), jewel
 * sockets, keystones (rule changers) and, at the rim, a repeatable mastery for endless points.
 * Two rings join the sectors so builds can travel. The layout is generated by code from the
 * tables below (deterministic), so adding a notable or a skill is a one-line change.
 */
import { mod, type Mod, type StatId, type Tag } from './stats';

export type NodeKind = 'start' | 'minor' | 'notable' | 'keystone' | 'skill' | 'skillmod' | 'socket' | 'mastery';
export type Sector = 'str' | 'str_dex' | 'dex' | 'dex_int' | 'int' | 'int_str' | 'center';

export interface TreeNode {
  id: string;
  kind: NodeKind;
  name: string;
  x: number;
  y: number;
  sector: Sector;
  mods: Mod[];
  skill?: string;
  desc?: string;
  links: string[];
  /** Mastery nodes can be allocated any number of times. */
  repeatable?: boolean;
}

export interface Tree {
  nodes: TreeNode[];
  byId: Map<string, TreeNode>;
  start: string;
}

const SECTOR_ANGLE: Record<Exclude<Sector, 'center'>, number> = {
  str: 90, str_dex: 150, dex: 210, dex_int: 270, int: 330, int_str: 30,
};
export const SECTOR_COLOR: Record<Sector, string> = {
  str: '#e0584a', str_dex: '#e0a24a', dex: '#5ad06a', dex_int: '#4ac0c8', int: '#5a8aff', int_str: '#b06ae0', center: '#e8e4da',
};
export const SECTOR_NAME: Record<Sector, string> = {
  str: 'Might', str_dex: 'Bloodsport', dex: 'Finesse', dex_int: 'Shadow', int: 'Arcana', int_str: 'Zealotry', center: 'Origin',
};

// ---------------------------------------------------------------- content tables

type M = Mod;
const inc = (stat: StatId, v: number, tags?: Tag[]) => mod(stat, 'inc', v, tags);
const flat = (stat: StatId, v: number, tags?: Tag[]) => mod(stat, 'flat', v, tags);
const more = (stat: StatId, v: number, tags?: Tag[]) => mod(stat, 'more', v, tags);
const flag = (stat: StatId) => mod(stat, 'flag', 1);

/** Small nodes along spines and around wheels, per sector. */
const MINORS: Record<Exclude<Sector, 'center'>, M[][]> = {
  str: [[flat('str', 10)], [flat('life', 12)], [inc('damage', 10, ['physical'])], [inc('armor', 15)], [inc('damage', 10, ['melee'])], [flat('lifeRegen', 2)], [inc('stagger', 15)], [inc('area', 6)]],
  str_dex: [[flat('str', 6), flat('dex', 6)], [inc('damage', 10, ['attack'])], [flat('lifeLeech', 0.3)], [flat('bleedChance', 6)], [inc('attackSpeed', 4)], [flat('lifeOnHit', 2)], [inc('damage', 10, ['melee'])]],
  dex: [[flat('dex', 10)], [inc('attackSpeed', 4)], [inc('critChance', 12)], [inc('evasion', 15)], [inc('damage', 10, ['projectile'])], [inc('moveSpeed', 3)], [flat('poisonChance', 6)], [inc('cooldownRecovery', 4)]],
  dex_int: [[flat('dex', 6), flat('int', 6)], [inc('critChance', 12)], [inc('damage', 10, ['chaos'])], [flat('poisonChance', 6)], [inc('damage', 10, ['dot'])], [inc('castSpeed', 4)], [flat('critMulti', 8)]],
  int: [[flat('int', 10)], [flat('mana', 12)], [inc('damage', 10, ['spell'])], [inc('castSpeed', 4)], [inc('damage', 10, ['elemental'])], [inc('manaRegen', 15)], [flat('freezeChance', 3)], [flat('igniteChance', 5)]],
  int_str: [[flat('int', 6), flat('str', 6)], [inc('damage', 10, ['fire'])], [inc('damage', 10, ['lightning'])], [flat('resFire', 8)], [flat('resLightning', 8)], [inc('damage', 8, ['elemental', 'attack'])], [flat('shockChance', 5)]],
};

interface NotableDef { name: string; mods: M[] }
const NOTABLES: Record<Exclude<Sector, 'center'>, NotableDef[]> = {
  str: [
    { name: 'Iron Skin', mods: [inc('armor', 40), flat('life', 25), inc('stunThreshold', 30)] },
    { name: 'Heart of the Ox', mods: [inc('life', 10), flat('lifeRegen', 5)] },
    { name: 'Brutal Edge', mods: [inc('damage', 30, ['physical', 'melee']), inc('stagger', 25)] },
    { name: 'Earthbreaker', mods: [inc('area', 20), inc('damage', 20, ['area'])] },
    { name: 'Bloodied Resolve', mods: [more('damageTaken', -10, ['cond:lowLife']), flat('lifeRegenPct', 1.5)] },
    { name: 'Juggernaut', mods: [inc('armor', 30), inc('knockback', 40), flat('cannotBeStunned', 0)] },
    { name: 'Warlord\'s Voice', mods: [inc('cooldownRecovery', 15, ['warcry']), inc('damage', 25, ['warcry'])] },
    { name: 'Colossus', mods: [inc('life', 8), flat('str', 20)] },
    { name: 'Crushing Blows', mods: [inc('critMulti', 0), flat('critMulti', 25, ['melee']), inc('damage', 15, ['vs:elite'])] },
  ],
  str_dex: [
    { name: 'Bloodthirst', mods: [flat('lifeLeech', 1), inc('damage', 15, ['attack'])] },
    { name: 'Razor\'s Dance', mods: [inc('attackSpeed', 10), flat('bleedChance', 15)] },
    { name: 'Gladiator', mods: [flat('block', 6), inc('damage', 20, ['melee'])] },
    { name: 'Carnage', mods: [inc('damage', 30, ['vs:bleeding']), flat('lifeOnKill', 10)] },
    { name: 'Second Wind', mods: [inc('moveSpeed', 6, ['cond:recentKill']), inc('attackSpeed', 10, ['cond:recentKill'])] },
    { name: 'Duelist\'s Grace', mods: [inc('evasion', 25), inc('armor', 25), inc('attackSpeed', 6)] },
    { name: 'Rampage', mods: [inc('damage', 25, ['cond:recentKill']), flat('lifeOnKill', 6)] },
  ],
  dex: [
    { name: 'Quickstep', mods: [inc('moveSpeed', 8), flat('dodgeCooldown', -0.1)] },
    { name: 'Deadeye', mods: [inc('damage', 25, ['projectile']), inc('projectileSpeed', 20)] },
    { name: 'Assassin\'s Edge', mods: [inc('critChance', 35), flat('critMulti', 20)] },
    { name: 'Wind Dancer', mods: [inc('evasion', 40), more('damageTaken', -5)] },
    { name: 'Serpent\'s Fang', mods: [flat('poisonChance', 20), inc('damage', 25, ['dot'])] },
    { name: 'Hunter\'s Instinct', mods: [inc('damage', 20, ['cond:moving']), inc('moveSpeed', 4)] },
    { name: 'Flicker Strike', mods: [inc('attackSpeed', 12), inc('cooldownRecovery', 10)] },
    { name: 'Sharpshooter', mods: [flat('pierce', 1), inc('damage', 15, ['projectile'])] },
    { name: 'Evasive Roll', mods: [more('damageTaken', -10, ['cond:recentDodge']), inc('damage', 20, ['cond:recentDodge'])] },
  ],
  dex_int: [
    { name: 'Venom Lore', mods: [inc('damage', 30, ['chaos']), flat('resChaos', 15)] },
    { name: 'Lethal Precision', mods: [inc('critChance', 40, ['spell']), flat('critMulti', 20, ['spell'])] },
    { name: 'Virulence', mods: [inc('ailmentDuration', 20), inc('damage', 25, ['vs:poisoned'])] },
    { name: 'Night Stalker', mods: [inc('moveSpeed', 6), inc('damage', 20, ['cond:moving'])] },
    { name: 'Malediction', mods: [inc('ailmentEffect', 20), inc('damage', 15, ['dot'])] },
    { name: 'Swift Affliction', mods: [inc('castSpeed', 10), flat('poisonChance', 10)] },
    { name: 'Shadow Sight', mods: [inc('lightRadius', 30), inc('critChance', 20)] },
  ],
  int: [
    { name: 'Arcane Focus', mods: [inc('damage', 30, ['spell']), flat('mana', 25)] },
    { name: 'Pyromancy', mods: [inc('damage', 30, ['fire']), flat('igniteChance', 15)] },
    { name: 'Winter\'s Embrace', mods: [inc('damage', 30, ['cold']), flat('freezeChance', 8)] },
    { name: 'Stormweaver', mods: [inc('damage', 30, ['lightning']), flat('shockChance', 15)] },
    { name: 'Clarity of Mind', mods: [inc('manaRegen', 40), inc('cost', -10)] },
    { name: 'Quick Casting', mods: [inc('castSpeed', 12), inc('cooldownRecovery', 8)] },
    { name: 'Elemental Mastery', mods: [inc('damage', 20, ['elemental']), flat('penetration', 8)] },
    { name: 'Summoner\'s Pact', mods: [inc('minionDamage', 40), inc('minionLife', 30)] },
    { name: 'Spellshield', mods: [flat('resFire', 15), flat('resCold', 15), flat('resLightning', 15)] },
  ],
  int_str: [
    { name: 'Sacred Flame', mods: [inc('damage', 25, ['fire']), flat('addedFire', 3, ['attack'])] },
    { name: 'Thunder Oath', mods: [inc('damage', 25, ['lightning']), flat('addedLightning', 3, ['attack'])] },
    { name: 'Templar\'s Ward', mods: [flat('resFire', 12), flat('resLightning', 12), inc('armor', 20)] },
    { name: 'Righteous Fury', mods: [inc('damage', 20, ['elemental', 'melee']), inc('area', 10)] },
    { name: 'Zealous Conviction', mods: [inc('damage', 15), inc('cooldownRecovery', 8)] },
    { name: 'Conduit Soul', mods: [flat('chain', 1), flat('shockChance', 10)] },
    { name: 'Smiting Light', mods: [flat('igniteChance', 10), flat('shockChance', 10), inc('damage', 15, ['vs:elite'])] },
  ],
};

interface KeystoneDef { id: string; name: string; desc: string; mods: M[] }
const KEYSTONES: Record<Exclude<Sector, 'center'>, KeystoneDef[]> = {
  str: [
    { id: 'blood_magic', name: 'Blood Magic', desc: 'Skills cost Life instead of Mana. 20% increased maximum Life.', mods: [flag('bloodMagic'), inc('life', 20)] },
    { id: 'unwavering', name: 'Unwavering Stance', desc: 'Cannot be Staggered. Dodge Roll cooldown is much longer.', mods: [flag('cannotBeStunned'), flat('dodgeCooldown', 0.8), inc('armor', 30)] },
    { id: 'bastion', name: 'Bastion', desc: 'Take 15% less damage while Stationary; 10% reduced Movement Speed.', mods: [more('damageTaken', -15, ['cond:stationary']), inc('moveSpeed', -10), flat('block', 5)] },
  ],
  str_dex: [
    { id: 'resolute', name: 'Resolute Technique', desc: 'Your hits can\'t be evaded. Never deal Critical Strikes. 20% more Attack Damage.', mods: [flag('alwaysHit'), flag('noCrit'), more('damage', 20, ['attack'])] },
    { id: 'vaal_pact', name: 'Vaal Pact', desc: 'Life Leech is instant. You have no Life Regeneration.', mods: [flag('instantLeech'), flat('lifeLeech', 1), more('lifeRegen', -100), more('lifeRegenPct', -100)] },
    { id: 'berserker', name: 'Berserker\'s Oath', desc: '45% more Damage while on Low Life. Low Life threshold is 50%.', mods: [more('damage', 45, ['cond:lowLife']), flat('lowLifeThreshold', 15)] },
  ],
  dex: [
    { id: 'acrobatics', name: 'Acrobatics', desc: 'Dodge Roll has no cooldown. 30% more Evasion. 50% less Armour.', mods: [flag('dodgeNoCooldown'), more('evasion', 30), more('armor', -50)] },
    { id: 'barrage', name: 'Barrage Doctrine', desc: 'Skills fire 2 additional Projectiles. 25% less Projectile Damage.', mods: [flat('projectiles', 2), more('damage', -25, ['projectile'])] },
    { id: 'momentum', name: 'Momentum', desc: '20% more Damage while Moving; 10% less while Stationary.', mods: [more('damage', 20, ['cond:moving']), more('damage', -10, ['cond:stationary']), inc('moveSpeed', 10)] },
  ],
  dex_int: [
    { id: 'plague_saint', name: 'Plague Saint', desc: 'Immune to Chaos Damage. 30% chance to Poison. 30% more Damage over Time.', mods: [flag('chaosImmune'), flat('poisonChance', 30), more('damage', 30, ['dot'])] },
    { id: 'glass_cannon', name: 'Glass Cannon', desc: '30% more Damage. 25% less maximum Life.', mods: [more('damage', 30), more('life', -25)] },
    { id: 'headhunter', name: 'Headhunter\'s Creed', desc: 'Steal the modifiers of Rare monsters you kill for 20 seconds.', mods: [flag('stealMods'), inc('itemRarity', 0)] },
  ],
  int: [
    { id: 'elemental_overload', name: 'Elemental Overload', desc: '40% more Elemental Damage. Never deal Critical Strikes.', mods: [more('damage', 40, ['elemental']), flag('noCrit')] },
    { id: 'packleader', name: 'Packleader', desc: 'Minions deal 50% more Damage. You deal 20% less Damage.', mods: [more('minionDamage', 50), more('damage', -20)] },
    { id: 'spore_lord', name: 'Spore Lord', desc: '25% chance for enemies you kill to burst into allied spores.', mods: [flat('splitOnKill', 25), inc('minionLife', 30)] },
  ],
  int_str: [
    { id: 'avatar_fire', name: 'Avatar of Fire', desc: '50% of Physical Damage converted to Fire. 50% less Cold and Lightning Damage.', mods: [flat('physToFire', 50), inc('damage', 30, ['fire']), more('damage', -50, ['cold']), more('damage', -50, ['lightning'])] },
    { id: 'cataclysm', name: 'Cataclysm', desc: 'Enemies you kill have a 25% chance to explode. 20% increased Area of Effect.', mods: [flat('explodeOnKill', 25), inc('area', 20)] },
    { id: 'storm_avatar', name: 'Storm Avatar', desc: '50% of Physical Damage converted to Lightning. Shocks you inflict are stronger.', mods: [flat('physToLightning', 50), inc('ailmentEffect', 30, ['lightning']), flat('shockChance', 15)] },
  ],
};

interface SkillCluster { skill: string; mods: Array<{ name: string; mods: M[] }> }
const s = (id: string) => `skill:${id}` as Tag;
const SKILL_CLUSTERS: Record<Exclude<Sector, 'center'>, SkillCluster[]> = {
  str: [
    { skill: 'groundslam', mods: [{ name: 'Fissure', mods: [inc('area', 30, [s('groundslam')])] }, { name: 'Aftershock', mods: [inc('damage', 40, [s('groundslam')])] }, { name: 'Stunning Slam', mods: [inc('stagger', 80, [s('groundslam')])] }] },
    { skill: 'leapslam', mods: [{ name: 'Earthshaker', mods: [inc('area', 30, [s('leapslam')])] }, { name: 'Heavy Landing', mods: [inc('damage', 40, [s('leapslam')]), inc('stagger', 40, [s('leapslam')])] }, { name: 'Swift Leap', mods: [inc('cooldownRecovery', 35, [s('leapslam')])] }] },
    { skill: 'warcry', mods: [{ name: 'Rallying Cry', mods: [inc('cooldownRecovery', 40, [s('warcry')])] }, { name: 'Intimidate', mods: [inc('area', 40, [s('warcry')])] }, { name: 'Battle Rage', mods: [inc('damage', 15), flat('lifeRegen', 3)] }] },
  ],
  str_dex: [
    { skill: 'whirlwind', mods: [{ name: 'Cyclone', mods: [inc('area', 25, [s('whirlwind')])] }, { name: 'Tempest Blades', mods: [inc('attackSpeed', 20, [s('whirlwind')])] }, { name: 'Leeching Spin', mods: [flat('lifeLeech', 1, [s('whirlwind')])] }] },
    { skill: 'shieldcharge', mods: [{ name: 'Battering Ram', mods: [inc('knockback', 60, [s('shieldcharge')])] }, { name: 'Momentous Charge', mods: [inc('damage', 50, [s('shieldcharge')])] }, { name: 'Rebound', mods: [inc('cooldownRecovery', 40, [s('shieldcharge')])] }] },
  ],
  dex: [
    { skill: 'dashstrike', mods: [{ name: 'Phantom Step', mods: [inc('cooldownRecovery', 40, [s('dashstrike')])] }, { name: 'Twin Strike', mods: [inc('damage', 40, [s('dashstrike')])] }, { name: 'Lightning Lunge', mods: [flat('addedLightning', 2, [s('dashstrike')]), flat('shockChance', 20, [s('dashstrike')])] }] },
    { skill: 'bladefan', mods: [{ name: 'Fan of Steel', mods: [flat('projectiles', 2, [s('bladefan')])] }, { name: 'Barbed Knives', mods: [flat('bleedChance', 30, [s('bladefan')])] }, { name: 'Piercing Blades', mods: [flat('pierce', 2, [s('bladefan')])] }] },
  ],
  dex_int: [
    { skill: 'venomcloud', mods: [{ name: 'Miasma', mods: [inc('area', 40, [s('venomcloud')])] }, { name: 'Virulent Cloud', mods: [inc('damage', 40, [s('venomcloud')])] }, { name: 'Lingering Fumes', mods: [inc('ailmentDuration', 30, [s('venomcloud')])] }] },
    { skill: 'blink', mods: [{ name: 'Flicker', mods: [inc('cooldownRecovery', 50, [s('blink')])] }, { name: 'Arcane Haste', mods: [inc('castSpeed', 30, [s('blink')]), inc('moveSpeed', 5)] }, { name: 'Phase Shift', mods: [more('damageTaken', -5, ['cond:recentDodge'])] }] },
    { skill: 'bladevortex', mods: [{ name: 'Thousand Blades', mods: [inc('damage', 50, [s('bladevortex')])] }, { name: 'Wide Vortex', mods: [inc('area', 30, [s('bladevortex')])] }, { name: 'Serrated Edges', mods: [flat('bleedChance', 30, [s('bladevortex')])] }] },
  ],
  int: [
    { skill: 'frostnova', mods: [{ name: 'Deep Freeze', mods: [flat('freezeChance', 20, [s('frostnova')])] }, { name: 'Rimefall', mods: [inc('area', 30, [s('frostnova')])] }, { name: 'Cold Snap', mods: [inc('cooldownRecovery', 40, [s('frostnova')])] }] },
    { skill: 'chainlightning', mods: [{ name: 'Arc Weaving', mods: [flat('chain', 2, [s('chainlightning')])] }, { name: 'Overcharge', mods: [flat('shockChance', 40, [s('chainlightning')])] }, { name: 'Storm Surge', mods: [inc('damage', 40, [s('chainlightning')])] }] },
    { skill: 'icespear', mods: [{ name: 'Splitting Ice', mods: [flat('projectiles', 1, [s('icespear')])] }, { name: 'Shatter', mods: [inc('critChance', 60, [s('icespear')])] }, { name: 'Glacial Lance', mods: [flat('pierce', 2, [s('icespear')])] }] },
    { skill: 'spiritwolves', mods: [{ name: 'Alpha', mods: [inc('minionDamage', 40)] }, { name: 'Pack Bond', mods: [inc('minionLife', 40)] }, { name: 'Swift Hunt', mods: [inc('cooldownRecovery', 40, [s('spiritwolves')])] }] },
  ],
  int_str: [
    { skill: 'meteor', mods: [{ name: 'Cataclysmic', mods: [inc('area', 30, [s('meteor')])] }, { name: 'Starfall', mods: [inc('damage', 40, [s('meteor')])] }, { name: 'Quick Comet', mods: [inc('cooldownRecovery', 40, [s('meteor')])] }] },
  ],
};

/** Starting-skill enhancements near the center (Cleave and Fireball are known from the start). */
const CORE_SKILL_MODS: Array<{ sector: Exclude<Sector, 'center'>; skill: string; mods: Array<{ name: string; mods: M[] }> }> = [
  { sector: 'str', skill: 'cleave', mods: [{ name: 'Wide Arc', mods: [inc('area', 30, [s('cleave')])] }, { name: 'Rending Cleave', mods: [inc('damage', 40, [s('cleave')])] }, { name: 'Bloodletting', mods: [flat('bleedChance', 25, [s('cleave')])] }] },
  { sector: 'int', skill: 'fireball', mods: [{ name: 'Pyroclasm', mods: [flat('projectiles', 2, [s('fireball')])] }, { name: 'Searing Orb', mods: [flat('igniteChance', 40, [s('fireball')])] }, { name: 'Inferno', mods: [inc('area', 40, [s('fireball')])] }] },
];

const MASTERY: Record<Exclude<Sector, 'center'>, { name: string; mods: M[] }> = {
  str: { name: 'Mastery of Might', mods: [inc('life', 2), inc('damage', 2, ['melee'])] },
  str_dex: { name: 'Mastery of Blood', mods: [inc('damage', 2, ['attack']), inc('attackSpeed', 1)] },
  dex: { name: 'Mastery of Finesse', mods: [inc('critChance', 4), inc('evasion', 3)] },
  dex_int: { name: 'Mastery of Shadow', mods: [inc('damage', 3, ['dot']), inc('critChance', 3)] },
  int: { name: 'Mastery of Arcana', mods: [inc('damage', 2, ['spell']), inc('mana', 2)] },
  int_str: { name: 'Mastery of Zeal', mods: [inc('damage', 2, ['elemental']), inc('armor', 3)] },
};

// ---------------------------------------------------------------- layout

function buildTree(): Tree {
  const nodes: TreeNode[] = [];
  const byId = new Map<string, TreeNode>();
  const add = (n: Omit<TreeNode, 'links'>): TreeNode => {
    const node = { ...n, links: [] as string[], x: Math.round(n.x), y: Math.round(n.y) };
    nodes.push(node);
    byId.set(node.id, node);
    return node;
  };
  const link = (a: TreeNode, b: TreeNode) => {
    if (a.id === b.id || a.links.includes(b.id)) return;
    a.links.push(b.id);
    b.links.push(a.id);
  };
  const at = (r: number, deg: number) => ({ x: r * Math.cos((deg * Math.PI) / 180), y: r * Math.sin((deg * Math.PI) / 180) });
  const minorName = (m: M[]) => (m.length > 1 ? 'Versatility' : ({
    str: 'Strength', dex: 'Dexterity', int: 'Intelligence', life: 'Vitality', mana: 'Wisdom', armor: 'Toughness', evasion: 'Agility',
    attackSpeed: 'Swiftness', castSpeed: 'Incantation', critChance: 'Precision', critMulti: 'Lethality', damage: 'Force', lifeRegen: 'Recovery',
    lifeLeech: 'Leech', lifeOnHit: 'Vampirism', moveSpeed: 'Fleetness', stagger: 'Impact', area: 'Reach', cooldownRecovery: 'Celerity',
    manaRegen: 'Clarity', freezeChance: 'Rime', igniteChance: 'Kindling', shockChance: 'Static', poisonChance: 'Venom', bleedChance: 'Rend',
    resFire: 'Fire Ward', resLightning: 'Storm Ward', critMulti_: '',
  } as Record<string, string>)[m[0].stat] ?? 'Passive');

  const start = add({ id: 'start', kind: 'start', name: 'Origin', x: 0, y: 0, sector: 'center', mods: [] });
  const sectors = Object.keys(SECTOR_ANGLE) as Array<Exclude<Sector, 'center'>>;
  const innerRing: TreeNode[] = [];
  const outerRing: TreeNode[] = [];
  let socketN = 0;

  for (const sec of sectors) {
    const ang = SECTOR_ANGLE[sec];
    const minors = MINORS[sec];
    let mi = 0;
    const nextMinor = () => minors[mi++ % minors.length];
    const minorNode = (id: string, x: number, y: number) => {
      const m = nextMinor();
      return add({ id, kind: 'minor', name: minorName(m), x, y, sector: sec, mods: m });
    };
    // Spine: 13 nodes from r=110 to r=1010.
    const spine: TreeNode[] = [];
    for (let i = 0; i < 13; i++) {
      const p = at(110 + i * 75, ang + Math.sin(i * 0.9) * 2.5);
      spine.push(minorNode(`${sec}_sp${i}`, p.x, p.y));
      if (i) link(spine[i - 1], spine[i]);
    }
    link(start, spine[0]);
    innerRing.push(spine[2]);
    outerRing.push(spine[8]);

    // Wheel clusters off the spine, alternating sides.
    const notables = NOTABLES[sec];
    notables.forEach((nd, k) => {
      const i = 1 + Math.floor((k * 11) / notables.length);
      const side = k % 2 ? 1 : -1;
      const r = 150 + i * 75;
      const off = side * (15 + (k % 3) * 3) * (300 / Math.max(300, r));
      const c = at(r + 40, ang + off);
      const notable = add({ id: `${sec}_n${k}`, kind: 'notable', name: nd.name, x: c.x, y: c.y, sector: sec, mods: nd.mods.filter((m) => m.value !== 0 || m.kind === 'flag') });
      const wheel: TreeNode[] = [];
      const count = 4 + (k % 3);
      for (let j = 0; j < count; j++) {
        const a = (j / count) * Math.PI * 2 + (ang * Math.PI) / 180;
        wheel.push(minorNode(`${sec}_n${k}_w${j}`, c.x + Math.cos(a) * 46, c.y + Math.sin(a) * 46));
      }
      wheel.forEach((w, j) => link(w, wheel[(j + 1) % count]));
      link(notable, wheel[0]);
      link(notable, wheel[Math.floor(count / 2)]);
      // Attach the wheel to the closest spine node.
      let best = spine[0], bd = Infinity;
      for (const w of wheel) for (const sp of spine) {
        const d = Math.hypot(w.x - sp.x, w.y - sp.y);
        if (d < bd) {
          bd = d;
          best = sp;
          void w;
        }
      }
      let closest = wheel[0], cd = Infinity;
      for (const w of wheel) {
        const d = Math.hypot(w.x - best.x, w.y - best.y);
        if (d < cd) {
          cd = d;
          closest = w;
        }
      }
      link(closest, best);
    });

    // Skill clusters: a short branch ending in the skill node, enhancements fanning out past it.
    const clusters = [...SKILL_CLUSTERS[sec], ...CORE_SKILL_MODS.filter((c) => c.sector === sec).map((c) => ({ ...c, core: true }))] as Array<SkillCluster & { core?: boolean }>;
    clusters.forEach((cl, k) => {
      const i = 1 + ((k * 4) % 9);
      const side = k % 2 ? -1 : 1;
      const r = 110 + i * 75;
      const base = spine[i];
      const branchA = at(r + 10, ang + side * 23 * (400 / Math.max(400, r)));
      const b1 = minorNode(`${sec}_s${k}_b`, branchA.x, branchA.y);
      link(base, b1);
      const sp = at(r + 30, ang + side * 31 * (400 / Math.max(400, r)));
      const skillNode = cl.core
        ? b1
        : add({ id: `${sec}_s${k}`, kind: 'skill', name: cl.skill, x: sp.x, y: sp.y, sector: sec, mods: [], skill: cl.skill });
      if (!cl.core) link(b1, skillNode);
      cl.mods.forEach((m, j) => {
        const p = at(r + 30 + (j - 1) * 42, ang + side * (39 + Math.abs(j - 1) * -3) * (400 / Math.max(400, r)));
        const mn = add({ id: `${sec}_s${k}_m${j}`, kind: 'skillmod', name: m.name, x: p.x, y: p.y, sector: sec, mods: m.mods, desc: `${cl.skill} enhancement` });
        link(skillNode, mn);
      });
    });

    // Keystones: one at the spine tip, two on side branches near the rim.
    const ks = KEYSTONES[sec];
    const tip = spine[spine.length - 1];
    ks.forEach((k, j) => {
      const p = j === 0 ? at(1100, ang) : at(990, ang + (j === 1 ? -14 : 14));
      const node = add({ id: `ks_${k.id}`, kind: 'keystone', name: k.name, desc: k.desc, x: p.x, y: p.y, sector: sec, mods: k.mods.filter((m) => m.value !== 0 || m.kind === 'flag') });
      if (j === 0) link(tip, node);
      else {
        const via = at(930, ang + (j === 1 ? -9 : 9));
        const v = minorNode(`${sec}_k${j}`, via.x, via.y);
        link(spine[10], v);
        link(v, node);
      }
    });
    // Mastery past the main keystone (repeatable).
    const ms = MASTERY[sec];
    const mp = at(1185, ang);
    const mastery = add({ id: `mastery_${sec}`, kind: 'mastery', name: ms.name, x: mp.x, y: mp.y, sector: sec, mods: ms.mods, repeatable: true, desc: 'Can be allocated any number of times.' });
    link(byId.get(`ks_${ks[0].id}`)!, mastery);
    // Jewel sockets.
    for (const i of [5, 9]) {
      const p = at(110 + i * 75, ang + (i === 5 ? 9 : -10));
      const sock = add({ id: `socket${socketN++}`, kind: 'socket', name: 'Jewel Socket', x: p.x, y: p.y, sector: sec, mods: [] });
      link(spine[i], sock);
    }
  }

  // Rings between neighbouring sectors (minor nodes along arcs).
  const ring = (anchors: TreeNode[], radius: number, perGap: number, tag: string) => {
    for (let i = 0; i < anchors.length; i++) {
      const a = anchors[i], b = anchors[(i + 1) % anchors.length];
      const sa = SECTOR_ANGLE[a.sector as Exclude<Sector, 'center'>], sb = SECTOR_ANGLE[b.sector as Exclude<Sector, 'center'>];
      let span = sb - sa;
      if (span <= 0) span += 360;
      let prev = a;
      for (let k = 1; k <= perGap; k++) {
        const deg = sa + (span * k) / (perGap + 1);
        const p = at(radius, deg);
        const sec = (k <= perGap / 2 ? a.sector : b.sector) as Exclude<Sector, 'center'>;
        const m = MINORS[sec][(k + i) % MINORS[sec].length];
        const n = add({ id: `${tag}${i}_${k}`, kind: 'minor', name: minorName(m), x: p.x, y: p.y, sector: sec, mods: m });
        link(prev, n);
        prev = n;
      }
      link(prev, b);
    }
  };
  const order = (list: TreeNode[]) => [...list].sort((p, q) => SECTOR_ANGLE[p.sector as Exclude<Sector, 'center'>] - SECTOR_ANGLE[q.sector as Exclude<Sector, 'center'>]);
  ring(order(innerRing), 260, 3, 'ri');
  ring(order(outerRing), 710, 7, 'ro');
  return { nodes, byId, start: start.id };
}

export const TREE: Tree = buildTree();

/** Shortest unallocated path from the allocated set to `target` (node ids to allocate, in order). */
export function pathTo(allocated: ReadonlySet<string>, target: string, tree: Tree = TREE): string[] {
  if (allocated.has(target) && !tree.byId.get(target)?.repeatable) return [];
  const sources = allocated.size ? [...allocated, tree.start] : [tree.start];
  const prev = new Map<string, string | null>();
  const q: string[] = [];
  for (const s0 of sources) {
    prev.set(s0, null);
    q.push(s0);
  }
  for (let i = 0; i < q.length; i++) {
    const cur = q[i];
    if (cur === target) break;
    for (const n of tree.byId.get(cur)?.links ?? []) {
      if (prev.has(n)) continue;
      prev.set(n, cur);
      q.push(n);
    }
  }
  if (!prev.has(target)) return [];
  const out: string[] = [];
  for (let c: string | null = target; c && !allocated.has(c) && c !== tree.start; c = prev.get(c) ?? null) out.unshift(c);
  if (allocated.has(target) && tree.byId.get(target)?.repeatable) out.push(target);
  return out;
}

/** Nodes that can be refunded without disconnecting others from the start. */
export function canRefund(allocated: readonly string[], id: string, tree: Tree = TREE): boolean {
  const set = new Set(allocated);
  if (!set.has(id)) return false;
  const count = allocated.filter((x) => x === id).length;
  if (count > 1) return true;
  set.delete(id);
  const seen = new Set<string>([tree.start]);
  const q = [tree.start];
  for (let i = 0; i < q.length; i++)
    for (const n of tree.byId.get(q[i])?.links ?? [])
      if (set.has(n) && !seen.has(n)) {
        seen.add(n);
        q.push(n);
      }
  for (const a of set) if (!seen.has(a)) return false;
  return true;
}
